### ISSUE TITLE
App Registration Vs Managed Identity

### ISSUE THREAD

**Issue by mdurini-swisscom** [mozziemozz/TeamsPhoneAutomation#4]
This is not really an issue but i'm only curious.. i was looking to the logic behind your scripts. the fact that you create first of all the app registration instead of using the managed identity of the automation account is only to be able to 
- execute the setup with the same permissions / access rights of the future execution of the scripts as scheduled jobs
- run the scripts from the local machine for debugging purpose

correct?

**Comment by mozziemozz** [comment]
As far as I'm aware, a managed identity can only be assigned Ahure RBAC roles but not individual Graph Permissions. I think they're well suited for managing Azure but not neccessarily Microsoft 365. The Azure AD App gets assigned all the required permission to manage SharePoint sites and Teams. It does help with local debugging but because of the reasons I just mentioned it would have to be an Azure AD App without local debugging too.

**Comment by mozziemozz** [comment]
@mdurini-swisscom Did you manage to get it working with managed identity and Teams?

**Comment by mdurini-swisscom** [comment]
Hi @mozziemozz, i will be back to this topic / project next week, i will update you soon.

**Comment by mozziemozz** [comment]
Managed Identity does not support Get/Set-Cs* Cmdlets yet.
